name: test

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    linux:
        runs-on: ubuntu-24.04
        name: Ubuntu 24.04
        steps:
            -   name: Install Swift
                uses: tayloraswift/swift-install-action@master
                with:
                    swift-prefix: "swift-6.0.1-release/ubuntu2404/swift-6.0.1-RELEASE"
                    swift-id: "swift-6.0.1-RELEASE-ubuntu24.04"

            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Run pipeline
                run: .github/pipeline

    macos:
        runs-on: macos-15
        name: macOS
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Run pipeline
                run: .github/pipeline

    devices:
        runs-on: macos-15
        name: devices
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Build iOS
                run: |
                    swift --version
                    xcrun xcodebuild build -scheme "IP" -destination \
                        "generic/platform=ios"

            -   name: Build tvOS
                run: |
                    swift --version
                    xcrun xcodebuild build -scheme "IP" -destination \
                        "generic/platform=tvos"

            -   name: Build watchOS
                run: |
                    swift --version
                    xcrun xcodebuild build -scheme "IP" -destination \
                        "generic/platform=watchos"

